dist: trusty
sudo: required
language: node_js

node_js:
  - 12

os:
  - linux

stages:
  - name: install
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
  # - name: deploy
  #   if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: install
      name: install
      script:
      - npm install
      skip_cleanup: true
    - stage: release
      name: release
      script:
      - npm run build
      - npx semantic-release
    #   skip_cleanup: true
    # - stage: deploy
    #   name: build and deploy
    #   script:
    #   - npm run build
    #   - npm run zip
    #   - npm run tar
    #   - export ZIP_FILE=$(ls release-*.zip)
    #   - export TAR_FILE=$(ls release-*.tar.gz)
    #   deploy:
    #     provider: releases
    #     api_key: $GH_TOKEN
    #     file_glob: true
    #     files:
    #       - "${ZIP_FILE}"
    #       - "${TAR_FILE}"
    #     skip_cleanup: true
